# Dockerfile.backend
FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y bash curl && rm -rf /var/lib/apt/lists/*

COPY backend/ /app

RUN chmod +x run.sh

EXPOSE 8000

CMD ["./run.sh"]